version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push:
      enabled: false
    users:
    - collaborators
    - moderators
