version: '3'
services:
  sickchill:
    image: sickchill/sickchill:latest
    container_name: sickchill
    restart: unless-stopped
    ports:
      - 8081:8081
    user: "1000:1000" #optional change two numbers to match the user and group Sickchill should run as or delete this line to run as root
    volumes:
      - /docker/sickchill/data:/data
      - /docker/sickchill/downloads:/downloads
      - /docker/sickchill/tv:/tv
      - /docker/sickchill/cache:/app/sickchill/sickchill/gui/slick/cache
      - /etc/localtime:/etc/localtime:ro
