version: '2'

services:
  sickchill:
    image: sickchill/sickchill:latest
    build:
      context: .
      args:
        - SICKCHILL_UID=317
        - SICKCHILL_USER=sickchill
    container_name: sickchill
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      -  ${SICKCHILL_DIR}/data:/data
      -  ${SICKCHILL_DIR}/downloads:/downloads
      -  ${SICKCHILL_DIR}/tv:/tv
