from sickchill.views.config.anime import ConfigAnime
from sickchill.views.config.backup import ConfigBackupRestore
from sickchill.views.config.general import ConfigGeneral
from sickchill.views.config.index import Config
from sickchill.views.config.notifications import ConfigNotifications
from sickchill.views.config.post_processing import ConfigPostProcessing
from sickchill.views.config.providers import ConfigProviders
from sickchill.views.config.search import ConfigSearch
from sickchill.views.config.shares import ConfigShares
from sickchill.views.config.subtitles import ConfigSubtitles
