Archive: test/files/rar202-comment-psw.rar
  comment='RARcomment'
FILE: hdrlen=66 datlen=32
  flags=0x800c:PASSWORD,COMMENT,LONG,D64
  os=0:DOS ver=20 mode=0x20 meth=3 cmp=32 dec=7 vol=0
  crc=0x7a197dba (2048490938) date_time=2010-11-03 00:27:28
  name=FILE1.TXT
  comment='file1comment'
FILE: hdrlen=66 datlen=32
  flags=0x800c:PASSWORD,COMMENT,LONG,D64
  os=0:DOS ver=20 mode=0x20 meth=3 cmp=32 dec=7 vol=0
  crc=0x785fc3e3 (2019541987) date_time=2010-11-03 00:27:34
  name=FILE2.TXT
  comment='file2comment'
