Archive: test/files/rar5-dups.rar
R5_FILE: hdrlen=43 datlen=55 hdr_extra=11
  block_flags=0x0003:EXTRA,DATA
  name=stest1.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=3 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=55 dec=2048 vol=0
  crc=0xc5b7e6a2 (3317163682)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
R5_FILE: hdrlen=58 datlen=0 hdr_extra=26
  block_flags=0x0003:EXTRA,DATA
  name=stest2.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=0 dec=2048 vol=0
  crc=0x00000000 (0)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
  redir: type=FILE_COPY flags=0:- destination=stest1.txt
R5_FILE: hdrlen=58 datlen=0 hdr_extra=26
  block_flags=0x0003:EXTRA,DATA
  name=stest3.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=0 dec=2048 vol=0
  crc=0x00000000 (0)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
  redir: type=FILE_COPY flags=0:- destination=stest1.txt
R5_FILE: hdrlen=58 datlen=0 hdr_extra=26
  block_flags=0x0003:EXTRA,DATA
  name=stest4.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=0 dec=2048 vol=0
  crc=0x00000000 (0)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
  redir: type=FILE_COPY flags=0:- destination=stest1.txt
R5_FILE: hdrlen=58 datlen=0 hdr_extra=26
  block_flags=0x0003:EXTRA,DATA
  name=stest5.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=0 dec=2048 vol=0
  crc=0x00000000 (0)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
  redir: type=FILE_COPY flags=0:- destination=stest1.txt
R5_FILE: hdrlen=58 datlen=0 hdr_extra=26
  block_flags=0x0003:EXTRA,DATA
  name=stest6.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=0 dec=2048 vol=0
  crc=0x00000000 (0)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
  redir: type=FILE_COPY flags=0:- destination=stest1.txt
R5_FILE: hdrlen=58 datlen=0 hdr_extra=26
  block_flags=0x0003:EXTRA,DATA
  name=stest7.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=0 dec=2048 vol=0
  crc=0x00000000 (0)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
  redir: type=FILE_COPY flags=0:- destination=stest1.txt
R5_FILE: hdrlen=58 datlen=0 hdr_extra=26
  block_flags=0x0003:EXTRA,DATA
  name=stest8.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=0 dec=2048 vol=0
  crc=0x00000000 (0)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
  redir: type=FILE_COPY flags=0:- destination=stest1.txt
R5_FILE: hdrlen=58 datlen=0 hdr_extra=26
  block_flags=0x0003:EXTRA,DATA
  name=stest9.txt
  file_flags=0x0004:CRC32
  cmp_algo=0 cmp_meth=0 dict=0 solid=False
  os=0:WINDOWS mode=0x20 cmp=0 dec=2048 vol=0
  crc=0x00000000 (0)
  date_time=2011-06-12 09:53:33
  mtime=2011-06-12T09:53:33+00:00
  redir: type=FILE_COPY flags=0:- destination=stest1.txt
