ARG BASE_TAG=latest

FROM --platform=$TARGETPLATFORM sickchill/sickchill:$BASE_TAG AS base

RUN \
 pip download sickchill --dest /wheels &&\
 find /wheels -type f -name "*none-any.whl" -delete &&\
 find /wheels -type f -name "*.gz" -delete

FROM scratch AS export-wheels
COPY --from=base /wheels /

