FROM --platform=$TARGETPLATFORM sickchill/sickchill:docker_multistage_build AS base
RUN \
 pip download sickchill --dest /wheels &&\
 find /wheels -type f -name "*none-any.whl" -delete &&\
 find /wheels -type f -name "*.gz" -delete

FROM scratch AS export-stage
COPY --from=base /wheels /

