name: Build wheel

on:
  workflow_run:
    workflows: [Python Packaging]
    types: [completed, requested]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 1
          persist-credentials: false

      - name: Get new version string
        uses: miigotu/actions-calver@workflows
        id: next-version
        with:
          release: false
          pre: true
          draft: true
          date_format: "%Y.%m.%-d"
          patch_separator: "-"
          version_regexp: '^20[^\-]*$'
          release_branch: ${{ github.event.workflow_run.head_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install yarn
        run: npm install -g yarn

      - name: Setup Python + Poetry
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'poetry'
          cache-dependency-path: pyproject.toml

      # Cache Poetry venv
      - name: Cache Poetry virtual environment
        uses: actions/cache@v6
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-release-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            venv-release-

      - name: Install Poetry
        run: pipx install poetry

      - name: Build artifacts
        run: |
          poetry version ${{ steps.next-version.outputs.release }}
          yarn version --no-version-git-tag --no-commit-hooks --new-version ${{ steps.next-version.outputs.release }}
          poetry build
        env:
          YARN_VERSION_GIT_TAG: ""

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Result
          path: |
            dist/*.whl
            dist/*.tar.gz

      - name: Show changelog
        run: |
          echo "${{ steps.next-version.outputs.changelog }}"
