name: Get next version number

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        description: "Whether a release should be made"
        default: false
        type: boolean
      release_branch:
        default: ${{ github.branch }}
        description: The branch, tag or SHA to create the release and tag from
        type: string
      draft:
        description: "Whether the release should be a draft"
        default: false
        type: boolean
      pre:
        description: "Whether the release should be a pre-release"
        default: false
        type: boolean
      patch_separator:
        description: "Separator between version and patch level"
        default: false
        type: boolean
      date_format:
        description: "Posix format for release git tags and releases"
        default: "%Y.%m.%d"
        type: string
      version_regexp:
        description: "Posix format to match releases in git tags and github releases"
        default: '^20[^\-]*$'
        type: string

    outputs:
      draft:
        description: "Whether the release is a draft"
        value: ${{ jobs.version.outputs.draft }}
      pre:
        description: "Whether the release is a pre-release"
        value: ${{ jobs.version.outputs.pre }}
      release:
        description: "Whether a release was made"
        value: ${{ jobs.version.outputs.release }}
      message:
        description: "The changelog generated for the release message"
        value: ${{ jobs.version.outputs.message }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get new version string
        uses: miigotu/actions-calver@workflows
        id: next-version
        with:
          release: ${{ event.inputs.release }}
          pre: ${{ event.inputs.pre }}
          date_format: ${{ event.inputs.date_format }}
          patch_separator: ${{ event.inputs.patch_separator }}
