name: "Upgrade poetry and yarn dependencies"

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  depends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: "develop"
          token: ${{ secrets.PAT }}

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python + Poetry
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'poetry'
          cache-dependency-path: pyproject.toml

      - name: Upgrade dependencies
        run: |
          pip install poethepoet
          poe depup

      - name: Push changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update poetry (python) and yarn (npm) dependencies"
          commit_options: "--no-verify --signoff"
          file_pattern: |
            pyproject.toml
            yarn.lock
            package.json
          commit_user_name: miigotu
          commit_user_email: miigotu@gmail.com
          commit_author: miigotu <miigotu@gmail.com>
          push_options: "--force"
          disable_globbing: true
          add_options: "-u"
